# -*- coding: utf-8 -*-
"""number guess game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgevKkwA1mMdCjHbG-61vlvmiW1-rZS0
"""

print("Hello, python!")

import random
import sys

num = random.randint(1, 101)
#print(num)

count=1
input_num=-1

while(input_num != num):
    try:
      input_num = int(input("put the number you guess: "))
    except ValueError:
      print("your input is invalid. please enter a number!\n")
      continue

    if(input_num > num):
        print("the number is smaller....\n")
        count+=1
    else:
        print("the number is bigger....\n")
        count+=1
    if(count>5):
        print("YOU LOSE! the number is ", num)
        break

if(count<=5):
  print("You found the number! Your score is", 100-(count-1)*20)